### ISSUE TITLE
Denote effectiveness of our own moves vs current mon

### ISSUE THREAD

**Issue by burnhamrobertp** [besteon/Ironmon-Tracker#10]
While in battle when switched over to our mon, next to each move, it would be incredible to have an indicator to show which moves are 4x, 2x, 1/2x 1/4x and 0x

![image](https://user-images.githubusercontent.com/231052/164592158-1b438888-e3d0-4ae0-8d7b-e3ed06fc51f2.png)

(ignore fact that remoraid is fainted)

**Comment by bdjeffyp** [comment]
This is an interesting idea. If you could provide a mock up of what that would look like in the tracker, that would be helpful. The tracker is quite cramped and it can be tough to include this information in a way that is obvious to identify at a quick glance.

One issue I can see with this though is that some could say that this removes some of the "skill" from the game: having the knowledge of which attacks are more or less effective against certain Pokémon types. Granted, we already have tools in place to give us this information (charts, bots, etc.), but the use of the tracker to provide that information could be frowned upon, especially by Pie. I'd like to hear his thoughts on it before considering active development in this idea.

**Comment by besteon** [comment]
Implemented in [d0e7c37](https://github.com/besteon/Ironmon-Tracker/commit/d0e7c37cbfae9f1b9438cc13b759af0ae58c5b45)
