### ISSUE TITLE
Evolved pokemon's ability showing as pre-evo ability

### ISSUE THREAD

**Issue by Fellshadow** [besteon/Ironmon-Tracker#102]
Issue name is mostly self-explanatory

Someone in the ironmon discord reported that they had a nidorino which traced early bird that evolved into an arbok with thick fat. The arbok's ability on the tracker showed as early bird regardless of how many battles they entered

I suspect that it's relating to the personality value being used as the unique identifier for a pokemon in the newest tracker version, and perhaps this personality value remains the same over evolution so the tracker "thinks" it's the same pokemon

If this is the case, may have to have some logic to clear the pokemon's ability on evolution such that it updates in the next battle. There may be a memory address that could be read to determine an evolution has happened to trigger this logic? (perhaps one that indicates currently in the evolution animation or something)

**Comment by UTDZac** [comment]
**Version:**
Ironmon-Tracker v0.5.0

**Vod:**
https://www.twitch.tv/videos/1532450141
Roughly 2:48:30 timestamp onward

**Seed Information:**
Randomizer Version: 4.5.0
Random Seed: 100646044200297
Settings String: 319WRIEEjIBAAQABwCRAAKeBnsECQEAFAACCQAuEgAAAAAABRi45ATkAYYICTIGBAIyAAUAEEZpcmUgUmVkIChVKSAxLjGwV2lQ48M4ig==
