### ISSUE TITLE
Weather Ball ideally automatically changes type and power in the weather

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#113]
This is more of an investigation issue to see if it's at all possible to do.

The move Weather Ball changes type and power in the weather. Notably, if the weather isn't normal (or fog), it changes to 100 power and a type that matches that weather. Currently the user can learn about this information simply by clicking the move on the screen, however it would be convenient if the weather information could be read from the game and reflect in the weather ball move itself.

This is likely a two-part issue:
1. Determine if its possible to read in weather information during battle, and remain accurate even if the weather changes.
2. Rework how move data is displayed/drawn to the tracker screen. By default it matches a move id with the static move data, but we ultimately want this to be dynamic. I'm imaging a rework on how the move data is first calculated, then later the Drawing operation can simply draw what has already been calculated. This part is a good chunk of work.

EDIT: Adding in a note this "feature" should be part of the calculate variable damage option, so players who dont want the extra help can opt-out.

**Comment by Fellshadow** [comment]
Just to add as an extension, part 2 of this about having dynamic move data could also potentially be used to dynamically adjust move effectiveness in general for scenarios such as transform or conversion

**Comment by Fellshadow** [comment]
Got some information regarding reading weather info from the game, which should cover part 1 of this issue/investigation.

There's a memory address `gBattleWeather` which stores [battle weather flags](https://github.com/pret/pokefirered/blob/master/include/constants/battle.h#L207) and is 0 when no weather / out of battle. If multiple weather effects go off in a battle/turn this address updates for each one in turn, so should always give us the current weather in battle.

Done some reads of this memory address and it returned the following values which could be used in a lookup table to determine the current weather:

Ability weathers (WEATHER_[weather]_PERMANENT flags):
> Easy to test, just set vanilla Groudon, Kyogre, and Tyranitar as the 3 starters
- Drizzle -> 5
- Sand Stream -> 24
- Drought -> 96

Move-based weathers (WEATHER_[weather]_TEMPORARY flags):
- Rain Dance -> 1
- Sandstorm -> 8
- Sunny Day -> 32
- Hail -> 128

I got these values primarily from a FireRed rom, but only double-checked values in RSE for abilities, however the battle weather flags are the same between all of RSE/FRLG so should also return the same for the move-based weathers too

The addresses for `gBattleWeather` are as follows:
- Ruby/Sapphire (all revisions) -> `0x02024db8`
- FireRed/LeafGreen (all revisions) -> `0x02023f1c`
- Emerald -> `0x020243cc`
