### ISSUE TITLE
Enemy move revealed immediately as first rival fight begins

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#116]
Version: v.0.5.2
Game: FRLG

Two different streamers have run into this issue where very rarely they see move information for a Pokemon they shouldn't know about. This appears to happen exclusively in lab fights, even before the Pokemon are sent out. I wonder if this has something to do with reading in game data and a desync between tracking it.  It's possible this bug affects other pokemon but is seen most commonly in lab fights.

![image](https://user-images.githubusercontent.com/4258818/179666280-bb4e27d8-b95a-4d67-9805-6883b1b9cab0.png)
Source: https://www.twitch.tv/videos/1536104846

Unsure if this affects games other than FRLG.

**Comment by thisisatest1900** [comment]
i am pretty sure that something similar happened to me
it happned for a mon outside the lab in route 22 fighting against armaldo 
on the fight it showed all his moves i wasnt 100% concentrating so it could be that i missed him using moves but i doubt i would have missed all the 4 moves being used 
from what i am seeing in the clip the move has * so my guess in the move data it registered as learned at lvl 1 or something maybe it would help narrowing it down
