### ISSUE TITLE
Change font size / UI scaling

### ISSUE THREAD

**Issue by megacorvega** [besteon/Ironmon-Tracker#134]
I'm using Ironmon-Tracker on Pop_OS! with a recent dev build of BizHawk, and I'm wondering if there is an easy way to reduce the font size (or GUI scaling) of the tracker? Below is a screenshot showing the issue

![Screenshot from 2022-07-27 09-37-53](https://user-images.githubusercontent.com/55958126/181302618-57ac7aff-181a-460b-ada3-f9367917d893.png)

**Comment by Fellshadow** [comment]
ooh that's certainly not ideal, i think it's possibly mainly from the font itself which we've been told doesn't work too well on linux? (something we'd like to sort out somepoint if we can, we're currently using Franklin Gothic Medium)

In terms of where to try adjusting it, if you don't mind dipping into the tracker files itself all the constants for the GUI drawing (including font and font size) are in the [Constants.lua](https://github.com/besteon/Ironmon-Tracker/blob/main/ironmon_tracker/Constants.lua#L19) file in the ironmon_tracker folder, could try decreasing the font size there and seeing if it helps?

**Comment by megacorvega** [comment]
Ok great, thank you! Unfortunately lowering the font size just makes it near unreadable, even though it fixes the overrun. 

I tried a few different fonts as well:

Terminus (Bitmap): Same issue, only looks good at larger font sizes as well, which makes overrun worse.
Terminus (TTF): Same issue as the default font
Noto Mono: Same issue as the default font

Changing the font also breaks all the +, -, ^, etc. icons as well. I'll just have to deal with it for now.

**Comment by Fellshadow** [comment]
ah, sorry to hear that it didn't work there. Hopefully we can figure out font settings that work for linux in the near future

**Comment by thechucklingatom** [comment]
On linux you should be able to install the franklin gothic font (located [here](https://fontsgeek.com/fonts/Franklin-Gothic-Medium-Regular)) and it should clean up most things. You can modify the e grave in Constants.lua if it does not load correctly in the work Pokemon.

**Comment by Fellshadow** [comment]
Going to close this issue for inactivity / it has a solution posted by thechucklingatom.

I have also added a section in the install guide to give this info to Linux users [here](https://github.com/besteon/Ironmon-Tracker/wiki/Installation-Guide#linux-users) and a small note about installing the font on the main README (currently in staging as of this comment posting).

If you try the above and still have issues, feel free to re-open this and/or let us know!

**Comment by ifmissky** [comment]
Hello, I have a similar problem.
Everything else looks fine except e. 
I am using a non-English windows system and the fonts will still exist after I install them.

Sorry, I used google Translate, I hope you can understand what I mean.
![aaa](https://user-images.githubusercontent.com/22941821/212055617-d78c9ef7-9085-420e-a118-a14d679cad78.png)

**Comment by Fellshadow** [comment]
hey @ifmissky, what version of bizhawk are you using? If you're using 2.8 then perhaps try 2.9 which is currently on [pre-release](https://github.com/TASEmulators/BizHawk/releases/tag/2.9-rc2)

Not sure if it'd resolve the issue or not, but could be worth trying since 2.9 added support for special characters (among other things) whereas in 2.8 we had to encode them so maybe that's the issue? The latest version of the tracker should work in 2.9

**Comment by ifmissky** [comment]
When I updated to 2.9-rc2, the problem was solved, thank you very much.
![3333](https://user-images.githubusercontent.com/22941821/212060479-9f4592d0-99fa-460d-b9f5-da910cdafc2e.png)
