### ISSUE TITLE
Allow for cycling backward through types in Hidden Power

### ISSUE THREAD

**Issue by RizRL** [besteon/Ironmon-Tracker#141]
Whether it's a right-click, or some other hotkey, being able to cycle backward through typings in Hidden Power would be convenient.

**Comment by UTDZac** [comment]
Leaving a note that this should theoretically be possible since Bizhawk seems to know the difference between Left and Right mouse button presses. Worth investigating.

Example of how it currently captures left mouse clicks:
`local mouseInput = input.getmouse()`
`if mouseInput["Left"] then ...`

**Comment by Fellshadow** [comment]
Main issue with using right-click is this menu popping up: 
![image](https://user-images.githubusercontent.com/106463662/182594126-5f9bb4f7-3d78-4c6e-a78c-5209c583a63b.png)
may not necessarily stop the functionality but could be inconvenient lol

**Comment by UTDZac** [comment]
With an incoming feature to allow support for randomized Pokemon types and randomized moves (including their types), ideally we'd want to find a reasonable solution to being able to change a Type displayed anywhere. This way players can track types that they see on all enemy pokemon and each of their moves. Granted, this is likely out of scope for this simple request, which is totally fine. Just mentioning #130 to be considered alongside this.

**Comment by jtigues** [comment]
Adding that spaghetti put together a hidden power toggling for the gen 4 tracker which handles this well, if we wanted to try button solution instead of a click based one

**Comment by UTDZac** [comment]
Got around to adding some arrow buttons to allow cycling forward and backward for setting the Hidden Power type.

![image](https://user-images.githubusercontent.com/4258818/209067636-fe0a0d78-2984-455c-bf7b-03776ca8fe41.png)
