### ISSUE TITLE
QoL Visual Enhancements and Options

### ISSUE THREAD

**Issue by besteon** [besteon/Ironmon-Tracker#15]
- Do not show primary mon data in the tracker until its summary has been checked.
- Do not show enemy mon data in the tracker until the mon is visible on screen.

**Comment by pisss** [comment]
- mon typing
- symbols/labels to indicate typing, as coloration isn't always clear/distinct 


(fantastic little plugin btw!)

**Comment by besteon** [comment]
> * mon typing
> 
>     * symbols/labels to indicate typing, as coloration isn't always clear/distinct
> 
> 
> (fantastic little plugin btw!)

Mon typing has been implemented in v0.1.9.

**Comment by besteon** [comment]
Implemented by ae11d936b073a1861594b1773c8ce773f12162ce
