### ISSUE TITLE
Error and freeze in new version

### ISSUE THREAD

**Issue by brdy1** [besteon/Ironmon-Tracker#162]
> Ironmon-Tracker v0.6.0a
> Waiting for ROM to be loaded...
> ROM Detected: Pokemon Fire Red v1.1
> No Tracker data found for this ROM. Initializing new data.
> NLua.Exceptions.LuaScriptException: ironmon_tracker/Utils.lua:320: attempt to perform arithmetic on a nil value

Ran into this error upon resetting using the A+B+Start+Select feature in the tracker. The data for the pokemon loaded, but one of the moves didn't load and the tracker is frozen at level 5.
When I try to toggle it off and on, the level updates but the last move is still empty and I get the same error:

> Ironmon-Tracker v0.6.0a
> Waiting for ROM to be loaded...
> ROM Detected: Pokemon Fire Red v1.1
> Tracker data loaded from file: Pokemon FireRed AutoSave.tdat
> NLua.Exceptions.LuaScriptException: ironmon_tracker/Utils.lua:320: attempt to perform arithmetic on a nil value

**Comment by brdy1** [comment]
Oh and I'm sure you will figure this out but the move is Eruption.

**Comment by UTDZac** [comment]
Thanks for the report. This was an issue with one of the recent feature supports included for reading in ability/move data. It should been fixed as of now, and that fixed version is available in the same [latest release](https://github.com/besteon/Ironmon-Tracker/releases/latest) download link.

Here is the fix: #158
