### ISSUE TITLE
Levitate not auto-tracking sometimes

### ISSUE THREAD

**Issue by Fellshadow** [besteon/Ironmon-Tracker#163]
Karlim encountered a levitate that didn't auto-track in v0.6.0 of the tracker - https://www.twitch.tv/videos/1556209752?t=0h39m7s

Order of events:
- Porygon 2 goes first (previous turn was hit by dragon rage)
- Porygon 2 uses bonemarang on crawdaunt
- Bonemarang misses due to levitate
- Levitate doesn't get auto-tracked, crawdaunt uses toxic

Levitate is a pain with auto-tracking since it doesn't run a unique script, so we currently check for the regular `BattleScript_HitFromAtkAnimation` script and look at the flags stored in `gMoveResultFlags` which for misses due to levitate, it will have a value of 9 (`MOVE_RESULT_DOESNT_AFFECT_FOE`  + `MOVE_RESULT_MISSED`)

Did a quick test and for me on FR 1.0 levitate auto-tracked correctly in v0.6.0 and v0.6.0a in brief testing

It's possible this was just a rare "once every so often" case where the tracker just didn't catch it, but noting here anyways in case there's a better way found to track levitate or this issue gets figured out

**Comment by jtigues** [comment]
Multi-hit moves like Bonemerang & Bone rush are only logging a gMoveResultFlags of 1 (MOVE_RESULT_MISSED)
Went back and checked and found:
gBattleCommunication[MISS_TYPE] = B_MSG_GROUND_MISS (aka gBattleCommunication + 0x6 = 4)
was present in all places where Levitate was triggered, so we can use this instead. Confirmed also that B_MSG_GROUND_MISS is not being used anywhere except for the Levitate activations, so no worries for Ground vs Flying false positives
