### ISSUE TITLE
io.popen() causing a crash in some cases

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#177]
Version: v0.6.1

It's possible that with the new version there exists a situation that when the Tracker first loads up (uncertain if this condition is true), the Tracker will crash with the following error:

> NLua.Exceptions.LuaScriptException: [string "main"]:10: 'popen' not supported

Which is erroring on this line exactly: `Main.Directory = os.getenv("PWD") or io.popen("cd"):read()`

I'm not sure why exactly, but opening this issue as something worth investigating, or at least something to keep an eye on as potentially more reports come in. It's possible this only affects certain PCs or setups, and not everyone.

Additional details from other users:
> "is it possible there's something wrong with the newest version? i saw it just got updated 2 hours ago and i've used it before successfully (that was on a different PC though, so this is a fresh install)"
> "i have no idea this is the first time im doing this"
> "i restarted my emulator and it worked 🤷"

**Comment by Fellshadow** [comment]
Seems this is the old config.ini issue resurfacing. 

When I moved my config.ini file out of my bizhawk folder (nothing else) a fresh download of v0.6.1 of the tracker won't load, producing this error.

Closing bizhawk (so that it makes a config.ini file) and reopening it, the tracker now works and loads correctly

Tested the same scenario but commenting out the line producing the error to see if the other io functions produced it and it worked fine, don't know why specifically `io.popen` doesn't work on bizhawk's first run (without a config.ini file)

**Comment by Fellshadow** [comment]
ok, can confirm that it's not the lack of config.ini specifically (wasn't sure how it could be tbh but it's the only visual difference we could see)

you can use config -> save config to generate a config.ini while bizhawk is open (and use load config to load it up), doing this does not make the tracker work

So it's something else bizhawk does in the background (relating to the config.ini maybe?) that's not done properly until it's gone through a complete open/close cycle

**Comment by UTDZac** [comment]
It's possible this one is out of our hands as something that can be fixed, especially if it magically occurs in Bizhawk background stuff.

For the time being, I've added a notification to the Tracker on first launch (first tracker launch) to inform the user that they need to close/reopen Bizhawk. https://github.com/besteon/Ironmon-Tracker/commit/33676a8c4a05d16d332ca79f675b7525e9eb1d96

**Comment by UTDZac** [comment]
While the core of this issue is still present because we will continue to use `popen`, this case has been covered by a First Run flag that shows the end-user how to avoid this error.

Closing this issue as resolved by alternate solution.
