### ISSUE TITLE
Route Info: Full information on Trainer's Pokémon team for a given route

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#185]
Version: 0.6.1

Similar to route info for wild encounters, the trainer info will show the available trainers you can fight on any given route. It can use the same Route Info Screen as wild encounters, simply as another encounter table for that route (this is partially implemented already; just empty).

I'm imagining the initial page for the route info screen while viewing trainer encounter table would show images of trainers (we'll need new images) and the # of Pokémon on their team. Clicking on a trainer image will change screens to a new page showing the trainer's full team of Pokémon (1-6), and the levels of each (the original levels in base games). Can potentially add additional information for important trainers, gym leaders, or elite four members, like whether they have smart AI or how many items they can potentially use in battle.

Am interested to know if there's other information that can be displayed here that would be helpful. Would also want to know if there's a better way to implement this for ease-of-use while still being information for challenge modes.

**Known Issues/Blocks:**
- Unsure how to represent or label a list of trainers for a given route such that the user can now which trainer is which within their game.
- We could also cross-off which trainers have already been fought, however, I currently do not know how to know what trainer the user is battling against. Surely this exists somewhere.
- Are there routes / floors of a building that exist that have more than a total of 10 trainers to fight? 10 is currently the limit used by wild encounters for a single page, but we might be able to display trainer info in a more condensed fashion.

**Comment by Fellshadow** [comment]
for trainer items: I made a list for FRLG [here](https://pastebin.com/knvmgKCi) from the [trainers.h](https://github.com/pret/pokefirered/blob/master/src/data/trainers.h) file in the decomp code, which stores them in the `gTrainers` struct (note that Ruby/Sapphire trainers are also stored here in FRLG for whatever reason, though obviously unused). 

The same file for RSE would also likely tell you the same info, if the RSE trainers in the FRLG file aren't the full data (Emerald would most certainly be different in places). That would be my starting point for what to look at for reading trainer data.

To note, if going to display the enemy team (non-vanilla data), would of course want to only show mons that have actually been seen, similarly to the route data. I'm sure you planned this anyways, but explicitly mentioning it for clarity.

> Unsure how to represent or label a list of trainers for a given route such that the user can now which trainer is which within their game.

Given that trainer names/classes can be randomised, it's tricky, but i think vanilla names/classes would be the most consistent (and would allow people to look them up on serebii/bulbapedia if they want to for seeing visually where they may be). Another thing that could help clarify is having a consistent/well-defined ordering of trainers (like, from east-west for example).

> We could also cross-off which trainers have already been fought, however, I currently do not know how to know what trainer the user is battling against. Surely this exists somewhere.

Going off of [this function in the decomp code](https://github.com/pret/pokefirered/blob/bc5426a3c6dc20d5dc7803721d9d68eb1abe4d87/src/battle_setup.c#L613) seems like (in FRLG anyways) the current trainer being fought gets stored in `gTrainerBattleOpponent_A`, which contains the same data defined in the above `trainers.h` file

> Are there routes / floors of a building that exist that have more than a total of 10 trainers to fight? 10 is currently the limit used by wild encounters for a single page, but we might be able to display trainer info in a more condensed fashion.

[Route 11](https://bulbapedia.bulbagarden.net/wiki/Kanto_Route_15#Generation_III_2) in FRLG (east of Fuschia) has 11 trainer fights, one of which is a double battle (though doubles could be lumped in as one trainer as the game itself does that, there's a "doubleBattle" flag in the trainer data). There's probably other routes with more than 10.

Checked my dungeon maps and none of the dungeons have more than 10 in any floor (not including lavender tower or sevii isles, though lavender tower i'm sure doesn't), not sure about gyms though.

**Comment by UTDZac** [comment]
Additional reference material, a Trainer Map made by an IronMon community user: https://kelseyyoung.github.io/FRLGIronmonMap/

**Comment by UTDZac** [comment]
As a quick feature addition, the Tracker now helps provide some small amount of details about the Trainer's current Pokémon team, such as how many total Pokémon there are and which ones have been KO'd.

From PR #354

**Comment by UTDZac** [comment]
For the time being, I'm going to close this issue. This sort of feature adds quite a bit of information, similar to what someone might fight in a walkthrough guide. I think one of the big goals of this feature was to help show information on the enemy team you were fighting, so you could check how many Pokemon were on their team and their levels. It's starting to feel a bit out of scope of what the tracker is "tracking."

With the recent addition of showing how many of a Trainer's pokemon team are remaining, I think that's good enough for me for having helpful information about a team at that given moment.

If someone wants to take on the project, feel free to reopen this issue.
