### ISSUE TITLE
Route Info: Some battles do not have a mapId or route name

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#191]
Version: 0.6.1

After playing for a bit and watching others play through the game, encountering pokemon from wild battles or trainer battles, there are a handful of areas I've noticed that show up as blank.

**[FRLG]** Areas that the player can engage in battle that have no route info (no route name/mapid):
- Each individual room within the S.S. Anne; outside areas appear to be fine
- The Game Corner rocket grunt at the entrance [Map Id = 27]

I suspect there may be more places that the player can engage in battle that show a blank route name, both in FRLG and RSE. Especially Sevii Islands.

Adding these might be a bit tricky. If I had a save file at these spots, then I could more easily just output the mapId to make sure we get the right one. Otherwise, I used this table of definitions for map stuff: https://github.com/pret/pokefirered/blob/918ed2d31eeeb036230d0912cc2527b83788bc85/include/constants/layouts.h

**Comment by Fellshadow** [comment]
Sevii Isles i'm currently working on, and will test once i put them in there just to note
