### ISSUE TITLE
Feature Request: Allow the tracker to create a new randomized seed on the fly

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#203]
Version: 0.6.1

The most common use-case for the Tracker loading the next seed is for the user to independently create a batch of multiple ROMs, in sequential order, and put them all in a single folder. Once they have completed this, they can assign the folder to the Tracker through the settings. This functionality works great and should not be changed.

Many users like making a single randomized game at a time instead of multiple. Thus they don't use the quick-load feature, but also cannot benefit from the quick-load, or rather fast reset feature that the Tracker offers. This feature request is to allow for this (concept came from a streamer)

The largest benefit of this feature addition would mean that, once its all setup properly, the user doesn't ever have to interact with the Randomizer program to make seeds. They can simply press the quick-load buttons to just create a new seed and begin playing.

### Research
Determine if it's possible within LUA to create a randomized ROM using the randomizer. Likely possible through the CLI tool, assuming a settings file has already been created.

### Implementation
For now, I'm mostly interested in how possible this is and less interested in finding spacing within the tracker settings to expose this feature. There is likely a lot of setup required behind the scenes to get this to work, such as putting the required randomizer files in a location that the Tracker can find, and having a `.rnqs` settings file made and ready to go.

**Comment by davidhouweling** [comment]
As per the ironmon discord thread, linking to a repo i started up pretty much at the same time as this feature request: https://github.com/davidhouweling/pokemon-randomizer-loader

**Comment by UTDZac** [comment]
@davidhouweling I've got the code foundation ready on the [203-create-randomized-seed-on-the-fly](https://github.com/besteon/Ironmon-Tracker/blob/203-create-randomized-seed-on-the-fly/) branch to include your feature code. It's up to you with how you want to implement it here, test it, and verify a number of use-cases work. I'm quite excited to get to try this out personally.

The main place to implement the new quick-load feature will be here:
https://github.com/besteon/Ironmon-Tracker/blob/56cd0c555cacf28e0f4469e03201c9569b96f60e/Ironmon-Tracker.lua#L250-L255

The file paths for everything needed are set by the user in the Tracker's settings menu. Notably, you need:
- `Options.FILES["Randomizer JAR"]`
- `Options.FILES["Source ROM"]`
- `Options.FILES["Custom Settings"]`

For now "Custom Settings" refers to the RNQS file that is required to have been created ahead of time. After we get this setup and near completion, I may add in pre-loaded RNQS files for common IronMon rulesets.

**Comment by UTDZac** [comment]
Closing out this branch as this feature has been completed by #211
