### ISSUE TITLE
[Feature Request] Happiness Tracking

### ISSUE THREAD

**Issue by dennisrijsdijk** [besteon/Ironmon-Tracker#25]
* Track Pokemon Happiness (useful for friend EVOs)

**Comment by bdjeffyp** [comment]
While I would be against showing the specific value (as it isn't displayed in game), I think we could update the tracker to show that evolution is possible once the happiness quota is met and evolution will happen at the next level up.

**Comment by dennisrijsdijk** [comment]
I've consulted with someone who shared the idea with me, and they agree with me that showing if a pokemon is ready to evo will still be very useful. I would recommend not to do it by coloring the friend evo text though, as that may cause issues for colorblind runners.

**Comment by bdjeffyp** [comment]
Awesome! And yes, we are working hard on supporting colorblind players as well because we want this challenge to be enjoyed by as many as possible. Thanks so much for your feedback. I will put myself down for working on this feature.

**Comment by bdjeffyp** [comment]
I went with using text to show that friendship evolution is about to happen. When friendship reaches and exceeds 220 in memory, the tracker switches from showing (FRND) to (SOON).

**Comment by dennisrijsdijk** [comment]
That's great, thank you so much!
