### ISSUE TITLE
Feature Request: Option to have randomized ball selection after loading next rom

### ISSUE THREAD

**Issue by haate** [besteon/Ironmon-Tracker#256]
Nothing fancy, just add an option to enable the function, with the function being as follows:
```
function Main.RandomNextBall
	if Options["Choose Next Ball"] then 
		if seedRolled then
			goto seeded
		else
			math.randomseed(os.time)
			seedRolled = true
		end
		
		::seeded::
		local choice = math.random(1,3)
		if choice == 1
			then ball = "Left"
		elif choice == 2
			then ball = "Middle"
		else
			ball = "Right"
		end
		
		print "For this run, you will be using the " .. ball .. " Ball! All hail " .. ball .. " gang!"
	end
end
```

the ::seeded:: bit is just because lua lacking a "continue" function (at least, as of 5.2), and, obviously, the text is free for modification. 

opinions, thoughts?

**Comment by UTDZac** [comment]
This is a feature that I have been thinking about adding recently. It's a good idea.

The main concern is where to show the outcome. Having things displayed in the Lua Console isn't ideal, as not many people use that or understand the console. Ideally this would be displayed somewhere on the Tracker screen itself, and only when contextually relevant. This has been the primary blocker for us, determine where to put it. I have some initial guesses, but managing screen real estate is always challenging.

**Comment by haate** [comment]
That the conversation was already being had would make ENTIRELY too much sense :D. 

Initially, my thoughts were to have it pop open a url to a wheel that some streamers use, but I couldn't find one that would just go without intervention/interaction, and that's just not something I think would be conducive to speed; ergo just the simple display. 

I would think that mayhaps displaying as an overlay to the tracker [i.e. redrawing the 'tracker' screen to do the display for a few seconds, and then going back to the standard blank tracker] could work, but, not having looked at the full details on how the tracker is displayed, I'm not sure of the viability of such.

maybe i should take a gander into that as well, rather than just blasting the idea into the aether and hoping someone knows how to do it already :)

**Comment by UTDZac** [comment]
Here's a sneak preview of what this will look like. Works for all games, RSE and FRLG. The random ball picker only appears if the player doesn't have any Pokémon and when the player's character is in "the lab" which is in Oak's lab building, or on route 101.

This can be disabled through the Tracker settings "Show random ball picker"

![image](https://user-images.githubusercontent.com/4258818/194806845-a550d3a2-f74a-4721-9f43-9b5aef809c41.png)

![image](https://user-images.githubusercontent.com/4258818/194806430-b1d685ae-9bd4-4131-b5a0-2de43112a44b.png)

**Comment by haate** [comment]
y'all rock!

**Comment by UTDZac** [comment]
Here is what the final version of the feature will look like. Has a minor grayed out effect for the Pokéballs that aren't the randomly selected starter ball. Mostly adding this reply so I can upload this image to add it elsewhere.

![image](https://user-images.githubusercontent.com/4258818/194925877-c97f8676-550a-40e7-b813-9b730ed53c38.png)
