### ISSUE TITLE
Automatically track the ability Inner Focus

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#269]
Currently when the enemy's **Inner Focus** ability triggers, it is not tracked. Ideally this should be tracked automatically.

Here are the list of moves that can cause a flinch:
- Stomp
- Rolling Kick
- Headbutt
- Bite
- Bone Club
- Sky Attack
- Rock Slide
- Hyper Fang
- Snore
- Twister
- Fake Out
- Secret Power (Cave)
- Needle Arm
- Astonish
- Extrasensory

**Comment by jtigues** [comment]
Issue has been fixed, just leaving a note here that only moves with a guaranteed secondary effect proc will trigger relevant ability messages.
I.e. zap cannon will cause limber's message to display, but thunderbolt never will. Ability Tracking doesn't care about the moves used anyway though so all bases should be covered

**Comment by UTDZac** [comment]
Closing as resolved in v6.5.0
