### ISSUE TITLE
[Feature Request] Colorblind option for nature-affected stats.

### ISSUE THREAD

**Issue by BridgetEndeavor** [besteon/Ironmon-Tracker#27]
For the sake of colorblind players as well as streamers wanting to make their tracker display more readable for colorblind viewers, an option to mark stats with a + and - instead of being color coded would be a nice feature.

**Comment by BridgetEndeavor** [comment]
Is bold an option? I realize that may also run into layout space limitations so it may not be feasible, but bold for positive stat, italics for negative stat I think would be easy enough to parse.  Otherwise I guess it's a factor of trying to establish what means what between the other options.

**Comment by bdjeffyp** [comment]
@BridgetEndeavor, let me know what you think about how this looks... I used bold for green and italic for red on the natures. I am concerned that the large pixel size of the font will make it harder to tell what is happening.
![image](https://user-images.githubusercontent.com/5532354/169672551-ec91fd8c-156c-404b-b974-71bc97daa489.png)

**Comment by BridgetEndeavor** [comment]
Oh yeah I think that offers some clarity and should be intuitive enough as to which means what.  I appreciate you taking the time to address this.

**Comment by bdjeffyp** [comment]
Fantastic! I have the code change up for review right now. Once it is approved and merged, this issue will be closed. Thanks so much for the idea to help improve this tracker for everyone.

**Comment by bdjeffyp** [comment]
Change is live in version 0.2.11. Closing.
