### ISSUE TITLE
Tracker does not track snatched moves

### ISSUE THREAD

**Issue by Fellshadow** [besteon/Ironmon-Tracker#271]
When the player uses Snatch and successfully steals a move from the enemy pokemon, the tracker does not track that move for the enemy pokemon

This is most likely due to the tracker considering the move as being used by the player pokemon and not capturing that the enemy used it at all (i.e. the enemy is only the "attacker" for a short time before it's given to the player)

Marking as low priority since it's not a very common scenario to occur lol more just noting this as a known issue

**Comment by UTDZac** [comment]
Closing as resolved in v6.5.0
