### ISSUE TITLE
Enhancement: Want to be able to mark a tracked stat as neutral

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#309]
Currently when marking a tracked stat for a Pokemon, you only have these three options, in order:
- _(leave empty)_
- Positive, indicated by a `+`
- Negative, indicated by a `-`

This enhancement would add a 4th option for **Neutral**, indicated by a `=` or maybe a circle like `o`. Not sure what would work best, or if `=` looks too much like `-`

![image](https://user-images.githubusercontent.com/4258818/205236402-c3cb9f9c-3fd6-420d-bc19-8de11b24c6ce.png)

**Comment by UTDZac** [comment]
This change will likely have conflicts with the large [mGBA addition and rewrite](https://github.com/besteon/Ironmon-Tracker/tree/utdzac/mgba-support-ohmy) I've been working on. Let me know if you plan to work on this and/or what it looks like afterwards so that I can prepare my code.

**Comment by Fellshadow** [comment]
isn't the empty option essentially the neutral option? or at least thats how myself and a bunch of other people have used it

**Comment by jtigues** [comment]
Adding the rest of the discussion here for posterity, other ideas:
- don't find a new icon for neutral, rather change the current "unknown" default to "?", and let the empty box be the new neutral
- could also use some other symbol for neutral like "~" or "■"

**Comment by UTDZac** [comment]
Feature enhancement is done and available in version 7.1.0.
