### ISSUE TITLE
Ironmon Tracker Licensing

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#341]
Hi!

You are mentioned here because you previously contributed to the [Besteon / Ironmon-Tracker Repo](https://github.com/besteon/Ironmon-Tracker), a Lua script for the Bizhawk/mGBA emulator.

### What is this issue:
There is a move to license the source of that repo under [MIT](https://opensource.org/licenses/MIT), and for that we need your permission, as past contributors.

To see the LICENSE that is being added: https://github.com/besteon/Ironmon-Tracker/blob/dev/LICENSE.txt _(included in v7.3.0 of the project)_

### What you need to do:
If you don't care, the best choice to do for the project and users of the project (researchers, fans, users, etc.) is to **agree**.

**If you agree**, you can reply to this issue with this message or one similar:

"I agree to share all my contributions to the Ironmon Tracker under MIT"

**If you disagree**, please get in touch! Through [GitHub issues](https://github.com/besteon/Ironmon-Tracker/issues) or [Ironmon Discord: Tracker dev thread](https://discord.com/invite/jFPYsZAhjX).

**Comment by UTDZac** [comment]
@besteon @UTDZac @Fellshadow @jtigues @Brian0255 @thisisatest1900 @AndreVolpi @schwjm @GB127 @kittenchilly @davidhouweling @moben @bdjeffyp @rcj001 

Important action required by you. Please see the original post above this message.

**Comment by UTDZac** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by moben** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by jtigues** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by davidhouweling** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by Fellshadow** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by bdjeffyp** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by schwjm** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by Brian0255** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by AndreVolpi** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by besteon** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by rcj001** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by GB127** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by kittenchilly** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by thisisatest1900** [comment]
I agree to share all my contributions to the Ironmon Tracker under MIT

**Comment by UTDZac** [comment]
That's everyone, thanks all.
