### ISSUE TITLE
Improve word choice/display of option text

### ISSUE THREAD

**Issue by Aeiiry** [besteon/Ironmon-Tracker#351]
[This comment applies moreso to every usage of this phrase and how it appears to the user]

I think the wording here could potentially be confusing to some users, though I do understand the limited space on the screen. Particularly "eff" may not be clear to some, and "dmg" is misleading as it's the power that's calculated, not damage (Further explanation on this latter part in the main review comment)

I'm not sure of a better phrasing off the top of my head but I wonder if having "Calculate effective pow/acc" would fit instead?

_Originally posted by @Fellshadow in https://github.com/besteon/Ironmon-Tracker/pull/350#discussion_r1114663060_

**Comment by Aeiiry** [comment]
oops I meant to add this to my own repo

**Comment by UTDZac** [comment]
One good note here brought up by this mention is that the options that are displayed to the user should allow for custom text, and not be tied strictly to the name of the option that is stored in the `Settings.ini` file. We did this for some future options, but I never retroactively fixed this for the `GameplayOptionsScreen`. At some point in the future, I intend to make it: 1) easier to display options and 2) easier to just add new options across the board.
