### ISSUE TITLE
Calm Mind (and Harden?)

### ISSUE THREAD

**Issue by VirtualViolet** [besteon/Ironmon-Tracker#374]
Had a run recently that had a weird bug/glitch where the opposing pokemon used Harden followed by Calm Mind (repeatedly), and the tracker did not recognize the Calm Mind and add it to the opposing pokemon's move list.

**Comment by UTDZac** [comment]
Thank you for the report. A few questions:

Q1. Do you have a screenshot showing the Tracker that shows the issue?

Q2. What version of the Tracker are you using? You can find this on the navigation menu page as soon as you click the Gear icon on the Tracker; its in the upper-right corner.

**Comment by VirtualViolet** [comment]
I don't have a screenshot, unfortunately. It was the version before today's update, whatever that was.

**Comment by UTDZac** [comment]
Could you share what pokemon game you were playing and what battle you were doing? If a wild, what route, if a trainer, which trainer?

Do you recall the events of the battle as they happened in order? Was this early in the battle, or pretty later in the battle such that a lot of other moves happened.

When the Calm Mind stopped tracking, you said it didn't show up in the move list. Did you see the calm mind stats get applied to the enemy Pokemon? Was the tracker still running at this point or was it frozen?

I have heard of anyone else run into this issue yet. I know enemy moves at one point had some issues with tracking, but that was fixed some time ago.

The exact tracker version number would be very helpful to know. If you were on 7.4.2, there shouldnt be an issue, but if this was the one you were on and there was an issue, this would be good to know. If you were on an older version then that version may have had the bug that was already fixed.

**Comment by VirtualViolet** [comment]
It was a patched version of Fire Red, the first rival battle in Oak's lab, the opponent used Harden on turn 1, then used Calm Mind multiple turns in a row, then Rest and Harden and Calm Mind some more (I don't remember what its 4th move was, but I'm pretty sure it was a special attack that immediately killed me when it finally used it, lol). Calm Mind was not added to the opponent pokemon's move list throughout the battle. I'm pretty sure the version was 7.4.2, since I only downloaded and installed the tracker in the first place like a week ago.

Sorry I don't have more information, but I didn't even think to report it until the tracker updated earlier and I came here to read the update notes.

**Comment by UTDZac** [comment]
No worries. That is helpful to know when and how it may have occurred. All the information helps. If we hear about it happening again, we can more easily piece together. This is a definitely a new one.

One other reason the tracker could just not work properly is if the rom you are playing is not a proper pokemon game rom. Perhaps it was randomized too many times and things got out of order. Perhaps a patch or two were applied poorly and weren't compatible, and caused things to change too much with the rom.

Any additional information about the state of your rom would be helpful too. However, at this point i dont know how to further investigate unless you are able to make the problem happen again.

**Comment by UTDZac** [comment]
For now I'm going to close this, as I think it is a fluke with an improperly randomized rom. If you are able to reproduce this consistently, let us know and we can investigate.
