### ISSUE TITLE
[Bug]: Ironmon Tracker on mGBA does not show if the moves are Special or Physical

### ISSUE THREAD

**Issue by FGigante2** [besteon/Ironmon-Tracker#402]
### Describe the bug

[Bug]: Ironmon Tracker on mGBA does not show if the moves are Special or Physical

### Steps to Reproduce

Just load a new game and watch it on the first pokemon you find

### What tracker version are you using?

v8.0.3

### What operating system are you using?

MacOS

### What emulator(s) are you seeing the problem on?

mGBA 0.10.1

### Relevant log output

```shell
No errors
```

**Comment by Fellshadow** [comment]
Thank you for the report, turns out this broke as part of the recent resources updates
Added a fix in dev branch - c4e51b6
