### ISSUE TITLE
[Bug]: Moves getting tracked from partner mon in doubles

### ISSUE THREAD

**Issue by Fellshadow** [besteon/Ironmon-Tracker#417]
### Describe the bug

Saw this in a FRLG doubles kaizo stream, probably affects RSE too unless it's a weird memory thing

Moves from one mon was being tracked on the other. In this case, metal sound from walrein was being tracked on muk and muk's bite was being tracked on walrein. Walrein learned metal sound at Lv.39 and muk learned bite at Lv.47

Moments I could find in VODs:
- [Lv.32 enemy muk showing metal sound on main screen](https://www.twitch.tv/videos/1935504853?t=03h34m54s)
- [20 mins later, viewing his own move history and metal sound shows on muk at Lv.45](https://www.twitch.tv/videos/1935504853?t=03h54m26s)
- [viewing move history of walrein, shows bite at Lv.47](https://www.twitch.tv/videos/1935596250?t=00h39m38s)
- [viewing move history of Lv.32 enemy muk, metal sound shows at Lv.45](https://www.twitch.tv/videos/1935596250?t=03h07m55s)

### Steps to Reproduce

Not sure on reproducing, but it seems to be doubles-mode-related

### What tracker version are you using?

8.3.0

### What operating system are you using?

Windows (not sure if 10 or 11)

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

### Additional Information

Given that it incorrectly showed on a main tracker screen once in addition to the move history, my guess is that it stems from the move tracking itself rather than displaying tracked info. Not sure where level 45 came from for metal sound though, since neither mon learns moves at that level. Best guess here is it mistakenly thought muk used it once when walrein used it

Worth noting that this streamer has one or two custom edits in their ROM which may/may not have affected something elsewhere in memory somehow, though still worth investigating if it's reproducable and a bug on our end

**Comment by UTDZac** [comment]
Here's another example of the move history screen having a move it shouldn't have https://clips.twitch.tv/TastyBreakableOctopusHotPokket-_Oiy9wxGJSZ9JsfS

**Comment by UTDZac** [comment]
Fixed in [v8.7.0](https://github.com/besteon/Ironmon-Tracker/wiki/Version-Changelog#version-870---release-info) via https://github.com/besteon/Ironmon-Tracker/pull/480/commits/27bff61766a8babde76c916bd3cb239478f48be1
