### ISSUE TITLE
Ruby/Sapphire support

### ISSUE THREAD

**Issue by DeadByte9** [besteon/Ironmon-Tracker#42]
I been doing over 100  ruby kaizo ironmon seeds its kind of dissapoting that these other gen 3 games are missing unlike emerald, ruby and sapphire have less double battles which makes the games less tedious and I think a tracker update to support these games would be huge

**Comment by besteon** [comment]
This can be accomplished using the symbol tables found here:
https://github.com/pret/pokeruby/tree/symbols

Although I'm not sure about the various versions and which are the most common, or how to detect which version is which.

**Comment by DeadByte9** [comment]
what do i do with the symbol table

**Comment by bdjeffyp** [comment]
@DeadByte9 That may have been directed at me. I am planning on working on getting these games supported so I will need this information to get the tracker working.

**Comment by bdjeffyp** [comment]
@DeadByte9 looking at the rom info for these games is showing that they aren't as well documented as Emerald and FRLG are. Unfortunately, this means that it will take a bit more time to get prepared than just changing some values. I should be able to make some progress on this over the weekend. Perhaps, if I get something workable, you'll be able and willing to help me test it?

**Comment by DeadByte9** [comment]
@bdjeffyp I'll be happy to help you test it

**Comment by bdjeffyp** [comment]
Made some progress tonight testing on Ruby v1.1!
![image](https://user-images.githubusercontent.com/5532354/170624199-3293120f-daf6-4d38-946b-538bfd49feca.png)
![image](https://user-images.githubusercontent.com/5532354/170624213-384f79bd-8db8-44b5-99a8-40c1cd680c24.png)
![image](https://user-images.githubusercontent.com/5532354/170624234-9f2f16d1-a2cf-432a-93eb-f989e38b4fe0.png)

**Comment by bdjeffyp** [comment]
@DeadByte9, if you are using Ruby v1.1, you can start testing now and seeing what things are or are not working. From [this link](https://github.com/besteon/Ironmon-Tracker/tree/user/bdjeffyp/add-ruby-sapphire-support), you can click on the green "Code" button and choose "Download ZIP" to get started.

Here are some of the things that need testing:
* [ ] Wild/trainer Pokémon appears automatically in tracker while the `AUTO_TRACK` setting is `true`.
* [ ] Opponent Pokémon moves populate the list as they are used.
* [ ] Opponent Pokémon moves update with new moves learned at later levels (you'll see a star next to the move name to know that it may be an old move).
* [ ] Your Pokémon data only appears after checking the summary if `MUST_CHECK_SUMMARY` setting is `true`.
* [ ] The tracker updates the Pokémon to show when switching between other Pokémon on the team. Additionally, the whole tracker is only revealed after checking the summary if `MUST_CHECK_SUMMARY` setting is `true`.
* [ ] HP of a poisoned Pokémon updates in the tracker with every damage taken.
* [ ] While there are known issues with the Heals in Bag feature, check to see that a potion or other healing item actually appears. I had to make an educated guess on which memory address to look at for this.

I think that covers it for now. Let me know if you have any questions.

**Comment by DeadByte9** [comment]
Ok I'll try it

**Comment by Fellshadow** [comment]
> Edit, I followed the link accordingly, and received a "Lua Error: Unsupported Game" When using Ruby version

@Dracobob8188 are you using a Ruby v1.1 english version ROM? that's the only Ruby/Sapphire version that's ready for testing rn according to the message above from bdjeffyp.

> Hi Folks, I've been playign Survival Ironmon on Ruby version for about 2 weeks now after playing Kaizo on FRLG. Would LOVE to test things out here as well. Anything I can help with?

I suppose just testing the things listed above and reporting here any bugs/issues you find (or even reporting if it's all working well would also be helpful)

**Comment by UTDZac** [comment]
I've been working on a ton of new updates to the Tracker, including performance improvements.  Within these updates I was able to add support for Ruby/Sapphire rev0 and rev2 of each, unsure if we also need rev1 (Rom v1.1?).
