### ISSUE TITLE
[Feature Request]: Fast Forward Option for battle intro

### ISSUE THREAD

**Issue by mdmurphy2** [besteon/Ironmon-Tracker#430]
### Tell us about your request

An option to allow fast forwarding of the battle intro scene.

### Additional Information

Many people use a turbo button / speed up when looking for pivots and I have found that this leads to eratic gameplay or could go too fast for some viewers

This feature would allow it so just the slowest part is fast forwarded automatically (The slide in + throwing of pokemon)

It also has the added benefit of speeding up trainer grinding

**Comment by mdmurphy2** [comment]
https://github.com/besteon/Ironmon-Tracker/pull/429

Also already created the code for review, as I accidentally did these steps out of order 😛

**Comment by mdmurphy2** [comment]
https://github.com/mdmurphy2/Ironmon-fastforward

**Comment by UTDZac** [comment]
This looks like a great idea to add to the Tracker Extensions wiki. I have a code update for you via discord. Let me know if the code update works for you and the extension still works, then update your github release, and i'll add this to the wiki.

**Comment by UTDZac** [comment]
Added to the Extensions list under: https://github.com/besteon/Ironmon-Tracker/wiki/Tracker-Add-ons
