### ISSUE TITLE
[Bug]: During battle the tracker doesn't show opposing pokemon. Just shows my party lead

### ISSUE THREAD

**Issue by nefariouslegion** [besteon/Ironmon-Tracker#433]
### Describe the bug

I have the option "Auto swap to enemy" enabled in the gameplay options but when I'm in battle the tracker just shows my lead pokemon instead of the opposition pokemon.

### Steps to Reproduce

1. Enable "Auto swap to enemy" in gameplay options
2. Go into battle
3. Here it should show my opposition pokemon but instead just shows my lead pokemon

### What tracker version are you using?

v8.3.8

### What operating system are you using?

Windows 11

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

**Comment by UTDZac** [comment]
I believe this is related to the issue posted in the Ironmon Discord, where a rom hack version of Emerald was being used, and it was incompatible with the Tracker. I'm closing this issue as a result.

If this isn't the case, let me know. And if you can, provide the game's log file found in your Tracker folder.
