### ISSUE TITLE
Opening ROM with Script Running Crashes Bizhawk

### ISSUE THREAD

**Issue by Yardomaster** [besteon/Ironmon-Tracker#44]
1. Open a Seed
2. Open Lua Window and open tracker script
3. File -> Open ROM, and select the file
4. Bizhawk almost always crashes trying to load the new ROM

(found in v0.2.1)

**Comment by besteon** [comment]
This is a known bug with Bizhawk 2.8. The workaround is to use the ROMS_FOLDER feature to cycle roms even quicker.
