### ISSUE TITLE
[Bug]: Text/Font sizing issues with linux

### ISSUE THREAD

**Issue by FIGBird** [besteon/Ironmon-Tracker#444]
### Describe the bug

BizHawk Version: 2.9.1
This is using the mono installation of bizhawk and the latest tracker installed with the install/update lua file. 

Everything seems to run properly, but the text sizing and/or font is off. I have attached a couple of screen shots to illustrate a few of the places its most noticeable. 

Comparing to some of the images I have seen via streamers it is unclear to me if it is a font issue or an issue with Lua itself sizing the font incorrectly. 

I have also confirmed this is an issue on two linux systems one running Mint and the other running pop_os!. In both cases the issue is identical as far as I can tell with the naked eye.

![Screenshot_20240207_122950](https://github.com/besteon/Ironmon-Tracker/assets/7865147/785bb51d-6625-4183-9514-07697eed6ebd)
![Screenshot_20240207_123541](https://github.com/besteon/Ironmon-Tracker/assets/7865147/3b0d82f2-fd09-4210-95c2-0935f6cc17e4)
![Screenshot_20240207_124502](https://github.com/besteon/Ironmon-Tracker/assets/7865147/65108f92-7400-47a2-99e1-5835984d0dfc)

### Steps to Reproduce

Load BizHawk
Enable the lua tracker
Load ROM (In my case it is Fire Red with the FasterFireRed 1.3 isp patch and auto name/gender from a wine launched patcher v1.2 )
View settings via cog wheel

Other places shown in screen:
clicking a move to view details
catching or otherwise obtaining a mon with an evo time

### What tracker version are you using?

8.4.2

### What operating system are you using?

Linux Mint/pop_os!

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

**Comment by Fellshadow** [comment]
First thing we want to check, do you have the Franklin Gothic Medium font installed as mentioned in our [installation guide](https://github.com/besteon/Ironmon-Tracker/wiki/Installation-Guide#notes-for-linux-users)? 
Since that's the font the tracker uses
