### ISSUE TITLE
[Bug]: Very poor performance on Linux BizHawk

### ISSUE THREAD

**Issue by GreenZanbato** [besteon/Ironmon-Tracker#445]
### Describe the bug

When running the tracker in the Linux version of BizHawk, the emulator can barely keep a normal fps, let alone fast forward. The FPS drops are constant but vary wildly, and streaming video elsewhere on the system exacerbates the issue.
I assume it has something to do with the way the tracker draws graphics, since non-graphical lua files have never caused any issues for me. There are no errors in any of the logs. Notably, this happens on the NDS tracker as well.

### Steps to Reproduce

1. Run EmuHawkMono.sh and load an Emerald ROM.
2. Launch tracker via lua console.
3. (Optional) Stream video in a browser or Discord.

### What tracker version are you using?

v8.4.2

### What operating system are you using?

Linux (Pop OS)

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

**Comment by UTDZac** [comment]
Thanks for the report. I have a few questions to understand the issue better:

1. Does this issue persist if you don't use the tracker at all? If so, it could be an issue with your Bizhawk setup
2. If it only occurs with the Tracker open, can you check the Lua Console's text output at the times when its slow or sluggish, its possible its reporting some errors there.
3. What setting is selected under Config > Display > Display Method? Mine is "Direct3D9"
4. Can you share a screenshot of the entire settings page under Config > Customize > Advanced tab? If there is an option for Lua Core, try changing it to the other option and test.

**Comment by GreenZanbato** [comment]
1. The issue only happens when the tracker is active.

2. This is the only output on the console: 
```
Loading Ironmon Tracker for Bizhawk (Gen 3)
Ironmon Tracker v8.4.2 successfully loaded
> Tracker Notes: Loaded from last play session.
```
3. The display method is OpenGL, since Direct3D9 is not supported in the Linux version.
4. Here is the requested screenshot:
![image](https://github.com/besteon/Ironmon-Tracker/assets/6954872/7bd3c360-03d4-4295-afe0-f1fdbe5f6a56)

(Unchecking "Run lua scripts when turboing" does allow turbo to hit a stable 550ish fps, but that doesn't really help when the game lags at normal speed or for fast forward.)

**Comment by UTDZac** [comment]
I'm not sure how to go about resolving this issue, as it appears its reliant on external factors outside of the Tracker script's control. As such, I'm closing this issue for now.

It's possible that not all Linux OS's are compatible with Bizhawk + Tracker script, given their different environments. If you were otherwise able to resolve this issue on your end, I'd be interested to hear how.
