### ISSUE TITLE
[Feature Request]: YouTube Compatibility for Stream Connect Chat Features

### ISSUE THREAD

**Issue by Kal-KrosswalkingKoboldsLLC** [besteon/Ironmon-Tracker#454]
### Tell us about your request

Currently the Stream Connect adds a command to Streamer Bot that can redirect appropriate commands to the Tracker. This command is compatible with YouTube chat as well:

<img width="367" alt="Screenshot 2024-04-15 152031" src="https://github.com/besteon/Ironmon-Tracker/assets/167132428/c715301a-bde3-42d5-9bac-c358e0003969">

At this time the Stream Connect feature is not set up to output to YouTube chat. I am not sure how this works through the tracker, but there is a sub action in streamer bot for outputting to YouTube Chat:

![image](https://github.com/besteon/Ironmon-Tracker/assets/167132428/5b2a6a6f-52aa-408d-b1c5-fe5ad45fd1f8)

I am not sure what it would take to do this, but can you please add YouTube Chat compatibility for the tracker? Thank you!

**Comment by UTDZac** [comment]
I was able to get this working and opened a PR to get this added #457 

Once its approved, it'll update the Tracker's beta test branch so that you and/or your friend can give it a test run
