### ISSUE TITLE
[Bug]: Incorrect position of the yellow highlight asterix in French language for possibles known moves of mon.

### ISSUE THREAD

**Issue by Zach0Dac** [besteon/Ironmon-Tracker#455]
### Describe the bug

The usual yellow highlight for the asterix is probably in the usual position for the English language, but it doesn't change to match the different lenght of the French word.
![Capture d’écran 2024-04-16 122032](https://github.com/besteon/Ironmon-Tracker/assets/166578861/eccc8567-41c5-462b-90ec-e199bdbe4ea0)

### Steps to Reproduce

1.Encounter a mon and scout some of its moves
2.Encouter the mon on a level with a different moveset and trigger the yellow highlight asterix for moves (not entirely sure what does it means or when it appears)
3.Be in French

### What tracker version are you using?

v8.5.1

### What operating system are you using?

Windows 11

### What emulator(s) are you seeing the problem on?

Bizhawk 2.8

**Comment by UTDZac** [comment]
Thanks for the bug report and the image showing the issue. This has been fixed in https://github.com/besteon/Ironmon-Tracker/commit/76c9c32160203ac2873d6f486c8a42b8f416a05e
