### ISSUE TITLE
[Bug]: Weird behavior of the "Speed" text in setup carousel tab

### ISSUE THREAD

**Issue by Zach0Dac** [besteon/Ironmon-Tracker#459]
### Describe the bug

I just noticed that it didn't translate the word "Speed" on the carousel tab of the setup screen. I thought I forgot to translate it, but all I found is LabelSpeedSetting = "Vitesse". Then I looked for other text in the code equal to "Speed", but the only other instance of "Speed" (outside of the word being part of bigger description like moves) was the SortSPE = "Speed" in LogSearchScreen and changing it didn't fix it. Then I tried changing LabelSpeedSetting in the English.lua, but it changed nothing neither for french or english language.
Edit: Just noticed that the tab's name aren't translated either even if they should be, and the exact same issue seems to applies. Changing the English.lua still won't affect the tab's name.
Other Edit: I am testing other tab's name and I think they all (or most of them) have the same issue. I tested the "tools" and "options" of the extraScreen, same issue.
Another Edit: Same thing for LabelInfoToShow
![Capture d’écran 2024-04-18 105214](https://github.com/besteon/Ironmon-Tracker/assets/166578861/f56ac038-1004-410b-b1f9-4076a2d8cf54)
![Capture d’écran 2024-04-18 110436](https://github.com/besteon/Ironmon-Tracker/assets/166578861/a9e1cf5a-0254-4302-8806-7506be4b2ef5)

### Steps to Reproduce

1. Go to the carousel tab in setup
2. Notice the word "Speed"
3. Go to French.lua in the setupScreen section
4. Notice the = "Vitesse",
5. Try changing language, changing the string for the labal or changing other instance of the string "Speed", probably nothing will change

### What tracker version are you using?

v8.5.2

### What operating system are you using?

Windows 11

### What emulator(s) are you seeing the problem on?

Bizhawk 2.8

**Comment by Zach0Dac** [comment]
Since it affects many texts, I am trying what they all have in common that other texts don't. So far my only idea is header? Most (if not all) of tab's name are affected (they are also highlighted when selected), "Speed" is kinda a header and "Info to show" is underline and introduce a list of settings. I have no idea if the tracker treats differently those "header", but I assume it does.

**Comment by UTDZac** [comment]
The original texts you found were correct. This was just a small bug with how the Tracker starts up and creates this screens initially. Some of the texts get locked in and never change, until you close and reopen the Tracker completely.

Fixed in https://github.com/besteon/Ironmon-Tracker/commit/acb9842a3af6a04003324572960a8a3a71886de7
