### ISSUE TITLE
[Bug]: Button "save" not sizing to the longer word "Enregistrer"

### ISSUE THREAD

**Issue by Zach0Dac** [besteon/Ironmon-Tracker#461]
### Describe the bug

It should display "Enregistrer", but it cuts the end because it is too long and only display "Enregistr". I would suggest to make the size to fit its content or simply make it bigger. Alternatively, I could replace the word "Enregistrer" for something shorter if it is hard to fix.
![image](https://github.com/besteon/Ironmon-Tracker/assets/166578861/d91cd39b-924b-4c66-af19-80214ac37d9c)

### Steps to Reproduce

1. Use my branch for the French translation or manually change "Save" variable in AllScreens for "Enregistrer"
2. In language, select "Français"
3. In streaming, click on a favorite to open the pop up
4. Notice the cut out word for the save button

### What tracker version are you using?

v8.5.2

### What operating system are you using?

Windows 11

### What emulator(s) are you seeing the problem on?

Bizhawk 2.8

### Additional Information

Other places where the save buttun is used also have the same issue, such as Edit attempts count or the welcoming message

**Comment by UTDZac** [comment]
This appears to be an issue with Bizhawk forms and Windows 11. I tested on Bizhawk 2.8 and 2.9.1 on my Win10 machine, and did not see the same problem.

![image](https://github.com/besteon/Ironmon-Tracker/assets/4258818/d203ca96-80a7-4ad4-bd0d-74b9b4dba658)

Closing this as won't/can't fix
