### ISSUE TITLE
[Bug]: Animated Pokemon Popup re-enables itself

### ISSUE THREAD

**Issue by Kal-KrosswalkingKoboldsLLC** [besteon/Ironmon-Tracker#465]
### Describe the bug

Animated Pop Out returns every run

### Steps to Reproduce

1. Open emulator
2. Load auto randomized rom
3. Open Lua Console
4. Load ironmon-tracker.lua
5. Press Start+A+B to randomize the game
6. Animated Pok... window appears
7. Open settings
8. Select Extras
9. Select Options tab
10. Uncheck Animated Pokemon Popout
11. Repeat from step 5

### What tracker version are you using?

8.5.3

### What operating system are you using?

Windows 10

### What emulator(s) are you seeing the problem on?

Bizhawk 2.9

### Relevant log output

```shell
My apologies, I was unable to locate the log files.
```

**Comment by UTDZac** [comment]
Do you use the Walking Pixel Pokemon extension? If so and if that is enabled, I think it can turn this on.

Otherwise, I may have to run some tests later this week.

If you can share any more additional details that could help as well.

**Comment by UTDZac** [comment]
I believe this is only a bug with the Walking Pixel Pokemon extension and not an issue with the regular Tracker. You're welcome to confirm, but I fixed this issue with the extension just now.

You can download and replace your extension here, this should fix the issue: https://github.com/UTDZac/IronmonTracker-WalkingPixelPokemon/releases/tag/v2.1

**Comment by Kal-KrosswalkingKoboldsLLC** [comment]
That fixed it! Thank you!
