### ISSUE TITLE
[Bug]: Weird carousel bahavior

### ISSUE THREAD

**Issue by Zach0Dac** [besteon/Ironmon-Tracker#467]
### Describe the bug

When walking in the map, the carousel box is always empty (and I think it should always be empty with my settings). But since in the begining it shows wild encounters of the area, after reaching safari I was confused why it wouldn't show up and that's how I realised clicking on it would open notes of the pokemon. After run away from a rod encounter, it would open the look up screen of the route. I am not entirely sure if it has anything to do with rod encounters, probably just which was the last one displayed before running away. Toggling on/off doesn't seems to fix anything, but I think it removes the clicking "event" of that empty box. I do not remember for defeated trainers, but I think it wasn't showing up after defeating one. It isn't allowing me to send a file bigger than 10MB, so I'll try to compress it later or else you can ask for it on discord: rider.of.fidji

### Steps to Reproduce

1. Reach post beginning of the game
2. Have the same settings as me?

### What tracker version are you using?

v8.5.3

### What operating system are you using?

Windows 11

### What emulator(s) are you seeing the problem on?

Bizhawk 2.8

**Comment by UTDZac** [comment]
Resolved with a band-aid fix for now. If there are other issues besides the empty Notes box pop-up when clicked, please open a new Issue with details on them.
