### ISSUE TITLE
Mirror Coat Bug

### ISSUE THREAD

**Issue by Tapollo** [besteon/Ironmon-Tracker#48]
Mirror Coat currently doesn't have the marker that it doesn't effect Dark types.

**Comment by bdjeffyp** [comment]
I can see why this is happening. We have logic to skip checking for effectiveness if the move doesn't have a Power stat, which Mirror Coat does not. Thanks for catching this. I have a fix coming out for this momentarily.

**Comment by bdjeffyp** [comment]
Addressed in pull request #51. Will close this issue once merged.

**Comment by bdjeffyp** [comment]
Merged fix. Will go out with release 0.2.3.
