### ISSUE TITLE
[Feature Request]: Note taking QoL Tweaks

### ISSUE THREAD

**Issue by Kensairabbit37** [besteon/Ironmon-Tracker#482]
### Tell us about your request

I play with controller, so written notes are a bit of a pain, going controller -> mouse > keyboard -> mouse -> controller. Here's two ideas to streamline the input process:
1. When you click on the note line to open it, have it open with the cursor ready to type. If enter or another hoykey could 'Save and close' that would be even better.
2. In conjunction, a hotkey would be even better to open and close. I know some commands for trainers and log menus were just added onto LR buttons. What if the Select button opened note taking during battle. I think it would specifically have to be on the main menu of battle (when it shows [Fight / Bag / Pokemon / Run]. Pressing Select would open up notetaking and then pressing again would 'Save and close'

**Comment by UTDZac** [comment]
Thank you for the QoL ideas. I agree, these seem great, however there are some complications with them. I've wanted to have these included for myself for some time, just can't figure out how to do it.

### "Have [the note box] open with the cursor ready to type"
This is a Bizhawk limitation. I cannot figure out how to do this with Bizhawk's internal lua `forms` functions. I have tried many different ways. I can try taking another look, but unsure how else to make it happen

Bizhawk's Lua functions: <https://tasvideos.org/BizHawk/LuaFunctions> (check the `forms` subsection)

### "If enter or another hotkey could 'Save and close'"
This is a Bizhawk limitation. Same answer as above. I have tried many solutions including `forms.setproperty()` with no success.

### "A hotkey would be even better to open and close [the notes box]"
This I could do, however it's a bit tricky. The biggest issue is finding a GBA button that can be mapped to this "Open/Close" function of the note taking box. SELECT does not work well, especially during battle. SELECT can reorder your moves on your Pokémon FIGHT screen in-game. SELECT also has different functions in Ruby/Sapphire/Emerald outside of battle than it does in Fire Red / Leaf Green. Even if a button binding could be found that didn't overlap with existing button bindings, you'll still have to stop using your controller to use the note taking feature (typing in text). I'm open to ideas on how to handle this, but there aren't many great options for making it work.

**Comment by UTDZac** [comment]
I'm closing this issue as "Can't Fix" due to limitations with the Bizhawk emulator. I've researched this one a few different times now and it simply doesn't seem possible with the lua integration support that the current Bizhawk version offers.

If in the future Bizhawk adds better support for control over form elements, I'll reopen and resolve this.
