### ISSUE TITLE
Tracker refresh of Pokémon midbattle after one is defeated not occurring

### ISSUE THREAD

**Issue by bdjeffyp** [besteon/Ironmon-Tracker#49]
During Kelpsey's recent stream: https://clips.twitch.tv/PiercingKitschyPeachFreakinStinkin-9a5EVDmUiUlV3qFa

**Comment by bdjeffyp** [comment]
It looks like the tracker is not refreshing when opponent Pokemon are switched in battle after the previous one is defeated

**Comment by bdjeffyp** [comment]
This might already be fixed in later versions of the tracker. Kelpsey isn't using version 0.2.2. I haven't seen this issue in my testing so far...

**Comment by GB127** [comment]
Would be helpful if the version of the tracker is shown somewhere tohelp with this kind of situation. Maybe a symbol that you change for each releases? (Like Version 1: Losange, Version 2: Square, Version 3 : heart). Just to help devs to determine if the last version is used.
