### ISSUE TITLE
Support other emulators

### ISSUE THREAD

**Issue by Zero3K** [besteon/Ironmon-Tracker#56]
I wonder if this could be made to support other emulators (such as mGBA, etc). If so, I hope you or someone else does it soon.

**Comment by GB127** [comment]
Not a dev, but I know some stuffs.

The other emulators needs to support lua... And that the said emulators has the same options offered in Bizhawk... If so, there is not a lot of writting needed to do, if any.

However, if something is changed (like how the gui text is named or it arguments order), then it will require a massive rewrite of everything, basically duplicating the code...).

In summary : Don't expect this to become reality. I doubt the maintainer will want this headache.

**Comment by bdjeffyp** [comment]
Thanks, GB127. It is exactly as they say, Zero3K. Adapting this to work in other emulators is unlikely as it would basically be a brand new project built from the ground up again.
