### ISSUE TITLE
Future Sight Bug

### ISSUE THREAD

**Issue by Tapollo** [besteon/Ironmon-Tracker#58]
Future Sight (I would assume Doom Desire) show that they are super effective, even though they are typeless damages.

~~KaizoFR.zip~~ (link removed)

![image](https://user-images.githubusercontent.com/104585947/171285636-76799c98-d21a-47cc-8e4d-1a5a6547f8fe.png)

To recreate this bug, pick Hariyama (Right Pokemon) go to Route 1 and one of the two Pokemon are Delcatty who has Future Sight.

**Comment by Tapollo** [comment]
@bdjeffyp this could be related to the fix you did for Sonic Boom.

**Comment by bdjeffyp** [comment]
Yep, and OnlySpaghettiCode is already on top of it in #59. Thanks so much, @Tapollo!

**Comment by GB127** [comment]
You may want to remove the link to the zip file. not sure if it's a good idea to leave these files around.
