### ISSUE TITLE
WT based power locks

### ISSUE THREAD

**Issue by CultGlutton** [besteon/Ironmon-Tracker#63]
if moves[moveIndex].power == "WT" and Settings.tracker.CALCULATE_WEIGHT_BASED_DAMAGE then
	if Tracker.Data.inBattle == 1 then
		local targetWeight = PokemonData[targetMon["pokemonID"] + 1].weight
		local newPower = Utils.calculateWeightBasedDamage(targetWeight)
		moves[moveIndex].power = newPower
	else
		moves[moveIndex].power = "WT"
	end
end

Once moves[moveIndex].power is set to newPower, it is no longer equal to "WT" and this if statement can't be true anymore. The power of the move gets stuck at the value for the first battle you enter. Perhaps adding power.type and power.value, one of which is displayed in battle and one out of battle? That would help with adding support for other alternate moves like hyperfang, dragon rage, counter, mirror coat, etc?

**Comment by Brian0255** [comment]
Thanks! This bug has already been fixed in the most recent version of the main branch by Fellshadow, who noticed the same thing yesterday.

**Comment by bdjeffyp** [comment]
Yep! The fix will be going out with a release soon. Thanks for bringing it up, CultGlutton!
