### ISSUE TITLE
Add calculations for hp-scaling moves

### ISSUE THREAD

**Issue by Fellshadow** [besteon/Ironmon-Tracker#67]
A suggestion was given in the ironmon discord to add calculations for other variable moves, in gen 3 these would be:

- [ ] Moves that get more power with more HP (water spout, eruption)
- [ ] Moves that get more power with less HP (flail, reversal)

There are also friendship-based moves (frustration and return) but those would give too much info imo so best not include calcs for those. Not sure if there are other moves that i'm forgetting that aren't just RNG-based like magnitude.

I'm willing to look into this and try to incorporate them when I find the time to, but putting this here to get your guys' inputs and in case someone else wants to tackle it before I can get to it (or at the very least as a reminder/note to myself) lol

In regards to user settings, I'm guessing lumping it into the weight-move calculation toggle in Settings.ini and re-naming the setting to something like "variable move calculations" would be the preferred approach rather than separate settings?

**Comment by bdjeffyp** [comment]
I agree with all of this, Fell. I think this is a good idea to implement, and 100% agree with the friendship moves NOT being included in this.
Lumping all of these types of moves into one setting is definitely the way to go as well.

**Comment by ETR-BTF** [comment]
I believe this issue can be closed now.

**Comment by Fellshadow** [comment]
yeah my bad, hadn't linked the PR fully to auto-close it and forgot lol
