### ISSUE TITLE
PokéCenter Heals Rule Change

### ISSUE THREAD

**Issue by bdjeffyp** [besteon/Ironmon-Tracker#79]
This: https://discord.com/channels/827408079272017930/833822819073654834/985968512289898526

Given that now PC heals don't apply until after the first non-rival trainer battle, we will need to make a change to my recent implementation of tracking PC heals.
@GB127 had suggested that this be done manually in my PR and I wanted it to be automatically tracked because nothing else in the Player's Pokémon page is tracked manually. Perhaps that'll have to change for now, until we can figure out a way to know if the player fought the first trainer outside of the rival fights. Unfortunately, I don't see a way to do that at the moment. Perhaps we could have the player tell the tracker to start tracking heals?

I'm asking for help on this because I am about to be unavailable for about two weeks. If anyone wants to take on improving the groundwork I laid, have at it! I will still be able to review/approve as long as you tag me in the PR. Thanks!

**Comment by valiant-code** [comment]
Having a way to tell the tracker to start sounds like a good option. It'd be good if it could be flexible with a way to manually adjust it if needed, as well as a way to turn auto mode off again. Unfortunately with my setup I can't contribute, but good luck to anyone who can take this on. 😄

**Comment by bdjeffyp** [comment]
Yes! All of that is an excellent idea! Obviously, space considerations are an issue with all of this as well, and GBA button configurations aren't going to be easy to adapt to using this, so it may take a bit more effort to get the Input class built up to better understand the overall state of the tracker. If it doesn't get done when I get back from my vacation, then I'll get it done.

**Comment by bdjeffyp** [comment]
Closing this as completed with #80. I think Fell's implementation solves the problem the best way we can with the immediacy of the changes to the rules.
