### ISSUE TITLE
Hidden Power text awkwardly visible on-screen

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#86]
This is a bug. The "Hidden Power" move text is visible sometimes (upper-left corner of the below image). 

This is likely a case of the text of the Button being rendered even though the text of the moves does not get rendered. In the below example, the must check summary setting was turned on which is why the moves aren't shown, but it doesn't prevent the buttons text from rendering.

![image](https://user-images.githubusercontent.com/4258818/174459735-30b6fa90-ae79-497b-8d20-62d65a7b503e.png)

One simple solution might be just adding an additional check for the `Tracker.Data.needCheckSummary` flag in the button's `visible` variable. This way the button won't be drawn until the moves are ready to be drawn, and therefore it's X and Y positions will be properly set.

https://github.com/besteon/Ironmon-Tracker/blob/91902fe423444eb36a69283f0baa65500047932a/ironmon_tracker/Buttons.lua#L30-L39

**Comment by Fellshadow** [comment]
noting that with the above PR being merged this can be closed now
