### ISSUE TITLE
Loading new rom crashes bizhawk

### ISSUE THREAD

**Issue by burnhamrobertp** [besteon/Ironmon-Tracker#9]
Start Ironmon Tracker script, in bizhawk go to file, open rom, select a different rom that you've generated, bizhawk will crash

Bizhawk 2.8 x64
Ironmon Tracker 0.1.4
FRLG 1.1

**Comment by besteon** [comment]
I believe a workaround is to disable the script (double click the name of the script in the Lua Console), then load a new ROM, then re-enable it.

I think this has to do with continuously polling memory locations, and once the ROM is unloaded it causes a crash.

**Comment by Yardomaster** [comment]
That is a workaround, but it's still quite a disruption to workflow, especially since you have to click on the main Bizhawk window after re-enabling the script (the lua window steals focus, even if you have background input enabled).

**Comment by besteon** [comment]
> That is a workaround, but it's still quite a disruption to workflow, especially since you have to click on the main Bizhawk window after re-enabling the script (the lua window steals focus, even if you have background input enabled).

This is a Bizhawk bug. It is outside of my current knowledge to fix it myself but I have reported it to the Bizhawk devs and will provide updates here if/when it gets fixed.

**Comment by besteon** [comment]
A code-workaround has been implemented in the master branch. Using File->Open ROM will still crash Bizhawk, but soft resetting the game via A+B+Start+Select will load the next rom from Settings.ROMS_FOLDER.

The workaround is to wait 5 seconds between opening the script and registering the event callbacks.

**Comment by besteon** [comment]
This bug is fixed in the master branch of Bizhawk (unreleased). The tracker workaround works well enough though.
