### ISSUE TITLE
Lua error when soft refresh to next rom

### ISSUE THREAD

**Issue by mycofiltrr** [besteon/Ironmon-Tracker#97]
I get an error saying that lua cant run in two host threads at a time, using bizhawk.
Once i exit the error, there are no other problems. Is there a way to disable the error?

**Comment by UTDZac** [comment]
Could you share what version of Bizhawk you are using, as well as the what version of the Ironmon Tracker you are using (it should say when you load it into bizhawk in the lua console).

I think this is a known issue with using older versions of Bizhawk, see here: https://github.com/besteon/Ironmon-Tracker#common-errors-and-solutions

**Comment by mycofiltrr** [comment]
im using bizhawk 2.8 and the tracker is v .3.31

**Comment by UTDZac** [comment]
Thanks for the response.

I'm not familiar with a version for 3.31. Are you using the other tracker by chance, the one for NDS games gen4/gen5? If so, you can learn more about that tracker here: https://github.com/Brian0255/NDS-Ironmon-Tracker

I believe there are some known issues at the moment where the tracker can have trouble soft-resetting to the next seed.

If all of this is not the case, and you are using this tracker (the one for gen3 games like FRLG and Emerald) then can you try updating to the [most recent release](https://github.com/besteon/Ironmon-Tracker/releases/latest)? There have been quite a number of bug fixes and improvements that should make this process more stable.

**Comment by mycofiltrr** [comment]
Yeah, im using the nds one. Thanks for the help though!
