### ISSUE TITLE
Make the next learned move and evo text easier to read

### ISSUE THREAD

**Issue by valiant-code** [besteon/Ironmon-Tracker#98]
The text in parenthesis for evolution and next learned move can be hard to see in a quick scan due to it not really standing out from all of the text around it.

I think ideally this text could be set to a different color, to set it apart from the rest of the information and provide a bit more visual grouping.

![Screen Shot 2022-07-12 at 11 32 18 PM](https://user-images.githubusercontent.com/58492441/178644981-1bfd72d2-99a1-4106-9640-c7de898e4bf2.png)

**Comment by UTDZac** [comment]
Resolved as part of #226
